import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const names = [
  ...readdirSync(join(repoRoot, "modules")).map((n) => `modules/${n}`),
  "dist/wloc.js",
  "dist/wloc-settings.js",
  "wloc.jpg",
];

const mime = (p) =>
  p.endsWith(".js")
    ? "application/javascript; charset=utf-8"
    : p.endsWith(".jpg")
      ? "image/jpeg"
      : "text/plain; charset=utf-8";

const entries = names.map((rel) => {
  const base = rel.split("/").pop();
  const b64 = readFileSync(join(repoRoot, rel)).toString("base64");
  return `  ${JSON.stringify(base)}: { mime: ${JSON.stringify(mime(rel))}, b64: ${JSON.stringify(b64)} }`;
});

const out = `// AUTO-GENERATED by scripts/gen-files.mjs — do not edit by hand
export const STATIC_FILES = {
${entries.join(",\n")}
};
`;
writeFileSync(join(repoRoot, "worker", "src", "static-files.js"), out);
console.log(`packed ${names.length} files -> worker/src/static-files.js (${out.length} bytes)`);
