#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭) | 快捷指令(推荐): 设置地理位置 https://www.icloud.com/shortcuts/4d8facdc933e4466841d7ada8e810e69 清理恢复位置 https://www.icloud.com/shortcuts/2a95780ae41b44bbb6a8c54175370bcc | 选点页面: https://wloc.zjun03321.dpdns.org/
#!author=zjun2024
#!homepage=https://github.com/zjun2024/wloc
#!icon=https://wloc.zjun03321.dpdns.org/files/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://wloc.zjun03321.dpdns.org/files/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://wloc.zjun03321.dpdns.org/files/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
