#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 选点页面: https://wloc-spoofer.zjun03321.workers.dev/
#!author=zjun2024
#!homepage=https://github.com/zjun2024/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/zjun2024/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/zjun2024/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
