#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 快捷指令(推荐): 设置地理位置 https://www.icloud.com/shortcuts/4d8facdc933e4466841d7ada8e810e69 清理恢复位置 https://www.icloud.com/shortcuts/2a95780ae41b44bbb6a8c54175370bcc | 选点页面: https://wloc.zjun03321.dpdns.org/
#!author=zjun2024
#!homepage=https://github.com/zjun2024/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/zjun2024/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/zjun2024/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
